apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: openstack-rabbitmq
  namespace: openstack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  override:
    service:
      spec:
        type: ClusterIP
  tls:
    secretName: rabbitmq-tls-secret
    caSecretName: openstack-ca-secret