apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-root-issuer
  namespace: openstack
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openstack-ca-cert
  namespace: openstack
spec:
  isCA: true
  commonName: "OpenStack-Internal-Root-CA"
  secretName: openstack-ca-secret
  issuerRef:
    name: selfsigned-root-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openstack-ca-issuer
  namespace: openstack
spec:
  ca:
    secretName: openstack-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-server-cert
  namespace: openstack
spec:
  dnsNames:
    - "rabbit.tls-nodes.openstack.svc.cluster.local"
    - "*.tls-nodes.openstack.svc.cluster.local"
    - "openstack-rabbitmq.openstack.svc"
    - "openstack-rabbitmq.openstack.svc.cluster.local"
    - "*.openstack-rabbitmq.openstack.svc.cluster.local"
  commonName: "rabbit.tls-nodes.openstack.svc.cluster.local"
  secretName: rabbitmq-tls-secret
  issuerRef:
    name: openstack-ca-issuer
    kind: Issuer