apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mariadb-operator/mariadb-operator.git
    targetRevision: v25.10.2
    path: deploy/charts/mariadb-operator
    helm:
      releaseName: mariadb-operator
      skipCrds: true
      values: |
        # Operator configuration
    
        # Resources for the operator
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # High availability
        replicas: 1

        # Webhook configuration
        webhook:
          enabled: true
          cert:
            certManager:
              enabled: false

        # Monitoring
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false

        # CRDs - disabled as they are installed separately
        crds:
          enabled: false

        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL

        # Pod security
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000

        # Service account
        serviceAccount:
          enabled: true
          automount: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
