apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ams0/openstack-native
    targetRevision: main
    path: clusters
    directory:
      include: 'rabbitmq-*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
