apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-users
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/ams0/openstack-native.git
      targetRevision: HEAD
      path: charts/secret-generator
      helm:
        releaseName: mariadb-basic-user
        values: |
          name: mariadb-basic-user
          namespace: openstack
    - repoURL: https://github.com/ams0/openstack-native.git
      targetRevision: HEAD
      path: charts/secret-generator
      helm:
        releaseName: mariadb-keystone-user
        values: |
          name: mariadb-keystone-user
          namespace: openstack
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: k8s.mariadb.com
      kind: MariaDB
      jqPathExpressions:
        - .status
