#!/bin/bash
set -euo pipefail

# Deploy one OpenStack-Helm service from the upstream chart, using this repo's
# values file with the REPLACE_WITH_* placeholders filled in from live cluster
# secrets. Rendered values are written to a temp file and never to the repo, so
# no password ever lands in git.
#
# Usage:  ./deploy-service.sh keystone [extra helm args...]
#         OSH_DIR=/path/to/openstack-helm ./deploy-service.sh glance
#
# The chart is taken from a local openstack-helm checkout (OSH_DIR). It is cloned
# on first use if absent, and `helm dependency update` is run so helm-toolkit is
# resolved from the sibling directory.

SERVICE="${1:?usage: $0 <service> [helm args...]}"; shift || true

NAMESPACE="${NAMESPACE:-openstack}"
CLUSTER_CONTEXT="${KUBECONTEXT:-kind-openstack-cluster}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OSH_DIR="${OSH_DIR:-${REPO_ROOT}/.openstack-helm}"
OSH_REF="${OSH_REF:-master}"
# Prefer a control-plane-specific values file when the repo ships one (neutron has
# both: neutron-values.yaml targets a full deployment with agents, while
# neutron-values-controlplane.yaml is server-only, which is what runs in-cluster).
if [ -z "${VALUES_FILE:-}" ] && [ -f "${REPO_ROOT}/values/${SERVICE}-values-controlplane.yaml" ]; then
  VALUES_FILE="${REPO_ROOT}/values/${SERVICE}-values-controlplane.yaml"
fi
VALUES_FILE="${VALUES_FILE:-${REPO_ROOT}/values/${SERVICE}-values.yaml}"
TIMEOUT="${TIMEOUT:-900s}"

GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${YELLOW}$1${NC}"; }
pass() { echo -e "${GREEN}✓ $1${NC}"; }
fail() { echo -e "${RED}✗ $1${NC}"; exit 1; }

[ -f "$VALUES_FILE" ] || fail "values file not found: $VALUES_FILE"

if [ ! -d "$OSH_DIR" ]; then
  info "cloning openstack-helm into ${OSH_DIR}"
  git clone --depth 1 --branch "$OSH_REF" -q https://opendev.org/openstack/openstack-helm.git "$OSH_DIR"
fi
[ -d "${OSH_DIR}/${SERVICE}" ] || fail "chart ${SERVICE} not found in ${OSH_DIR}"

info "resolving chart dependencies (helm-toolkit)"
helm dependency update "${OSH_DIR}/${SERVICE}" >/dev/null 2>&1 \
  || fail "helm dependency update failed for ${SERVICE}"

# Pull the live passwords. These are generated by scripts/setup-secrets.sh and by
# the RabbitMQ operator, so they differ on every cluster.
secret_val() {
  kubectl get secret -n "$NAMESPACE" --context="$CLUSTER_CONTEXT" "$1" \
    -o jsonpath="{.data.$2}" 2>/dev/null | base64 -d
}
MARIADB_ROOT_PASSWORD=$(secret_val mariadb-basic-root password)
RABBITMQ_ADMIN_PASSWORD=$(secret_val openstack-rabbitmq-default-user password)
RABBITMQ_KEYSTONE_PASSWORD=$(secret_val rabbitmq-keystone-user password)
# The RabbitMQ admin username is not stable across clusters: when the operator
# generates the default user it is named default_user_<random>. Substitute it
# rather than pinning a literal that goes stale the next time the cluster is
# rebuilt.
RABBITMQ_ADMIN_USERNAME=$(secret_val openstack-rabbitmq-default-user username)
: "${RABBITMQ_ADMIN_USERNAME:=admin}"
[ -n "$MARIADB_ROOT_PASSWORD" ] || fail "secret mariadb-basic-root not found — run 'make setup-secrets'"
[ -n "$RABBITMQ_ADMIN_PASSWORD" ] || fail "secret openstack-rabbitmq-default-user not found"

RENDERED=$(mktemp "${TMPDIR:-/tmp}/${SERVICE}-values.XXXXXX.yaml")
trap 'rm -f "$RENDERED"' EXIT
chmod 600 "$RENDERED"

# Substitute via python rather than sed: generated passwords contain characters
# that are awkward to escape for sed replacement strings.
python3 - "$VALUES_FILE" "$RENDERED" <<PY
import sys
src, dst = sys.argv[1], sys.argv[2]
text = open(src).read()
for placeholder, value in (
    ("REPLACE_WITH_MARIADB_ROOT_PASSWORD",    """${MARIADB_ROOT_PASSWORD}"""),
    ("REPLACE_WITH_RABBITMQ_ADMIN_PASSWORD",  """${RABBITMQ_ADMIN_PASSWORD}"""),
    ("REPLACE_WITH_RABBITMQ_KEYSTONE_PASSWORD", """${RABBITMQ_KEYSTONE_PASSWORD}"""),
    ("REPLACE_WITH_RABBITMQ_ADMIN_USERNAME",  """${RABBITMQ_ADMIN_USERNAME}"""),
    ("PASSWORD_PLACEHOLDER",                  """${MARIADB_ROOT_PASSWORD}"""),
):
    text = text.replace(placeholder, value)
open(dst, "w").write(text)
leftover = [l for l in text.splitlines() if "REPLACE_WITH" in l or "PASSWORD_PLACEHOLDER" in l]
if leftover:
    sys.stderr.write("unsubstituted placeholders remain:\n" + "\n".join(leftover) + "\n")
    sys.exit(1)
PY

# Layered on top of the base values; see values/overrides/kind-lab.yaml for why.
OVERRIDES="${OVERRIDES:-${REPO_ROOT}/values/overrides/kind-lab.yaml}"
override_args=()
if [ -n "$OVERRIDES" ] && [ -f "$OVERRIDES" ]; then
  override_args=(--values "$OVERRIDES")
  info "overlay: $(basename "$OVERRIDES")"
fi

info "helm upgrade --install ${SERVICE}"
helm upgrade --install "$SERVICE" "${OSH_DIR}/${SERVICE}" \
  --namespace "$NAMESPACE" \
  --kube-context "$CLUSTER_CONTEXT" \
  --values "$RENDERED" \
  "${override_args[@]}" \
  --timeout "$TIMEOUT" \
  "$@"

pass "${SERVICE} released"
echo ""
kubectl get pods -n "$NAMESPACE" --context="$CLUSTER_CONTEXT" \
  -l application="$SERVICE" 2>/dev/null | head -20
