apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keystone-helm-values
  namespace: openstack
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: openstack-secrets
    kind: SecretStore

  target:
    name: keystone-helm-values-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          endpoints:
            oslo_db:
              auth:
                admin:
                  username: root
                  password: "{{ .mariadb_password }}"
                keystone:
                  username: keystone
                  password: keystone
            oslo_messaging:
              auth:
                admin:
                  username: "{{ .rabbitmq_user }}"
                  password: "{{ .rabbitmq_password }}"
                keystone:
                  username: keystone
                  password: "{{ .keystone_rabbitmq_password }}"

  dataFrom:
    - extract:
        key: mariadb-basic-root
        property: password
        conversionStrategy: Default
      rewrite:
        - regexp:
            source: "password"
            target: "mariadb_password"

    - extract:
        key: openstack-rabbitmq-default-user
      rewrite:
        - regexp:
            source: "username"
            target: "rabbitmq_user"
        - regexp:
            source: "password"
            target: "rabbitmq_password"

    - extract:
        key: rabbitmq-keystone-user
        property: password
      rewrite:
        - regexp:
            source: "password"
            target: "keystone_rabbitmq_password"
